<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.1.86</Version>
    <PackageProjectUrl>https://github.com/Elagon-A/Penta-Penta</PackageProjectUrl>
    <Authors>Luis</Authors>
    <Description>Queue inventory gear and pentameld it with configurable stat priorities.</Description>
    <AssemblyName>PentaPenta</AssemblyName>
    <RootNamespace>PentaPenta</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
